# Użycie oficjalnego obrazu Node.js w wersji 20
FROM node:20-alpine

# Ustawienie katalogu roboczego
WORKDIR /app

# Kopiowanie plików package.json i package-lock.json
COPY package*.json ./

# Instalacja zależności
RUN npm install

# Kopiowanie pozostałych plików projektu
COPY . .

# Budowanie aplikacji
RUN npm run build

# Eksponowanie portu
EXPOSE 3000

# Uruchomienie aplikacji
CMD ["npm", "run", "start"]