"""Opis migracji

Revision ID: 4a23ff369947
Revises: ebc0d6244061
Create Date: 2025-08-18 06:41:28.910944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a23ff369947'
down_revision: Union[str, None] = 'ebc0d6244061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('koty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=32), nullable=False),
    sa.Column('rasa', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('koty')
    # ### end Alembic commands ###
