"""Opis migracji

Revision ID: 8fa26902233f
Revises: 16889c6899b5
Create Date: 2025-08-18 16:28:13.379180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa26902233f'
down_revision: Union[str, None] = '16889c6899b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('koty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('koty',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('imie', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('rasa', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='koty_pkey')
    )
    # ### end Alembic commands ###
