"""Opis migracji

Revision ID: c016c30ed2d7
Revises: 60a43cc6e74e
Create Date: 2025-08-20 22:13:46.696460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c016c30ed2d7'
down_revision: Union[str, None] = '60a43cc6e74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'owner_id')
    # ### end Alembic commands ###
